// This file was autogenerated by C:\xampp\htdocs\DecisionMaking\Apps\Transportation\web\libs\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../js/app.js', ['Transportation.App'], ['Transportation.Controllers.MyTableController', 'Transportation.Directives.MyTableDirective']);
goog.addDependency('../../../js/controllers/MyTableController.js', ['Transportation.Controllers.MyTableController'], []);
goog.addDependency('../../../js/directives/MyColDirective.js', ['Transportation.Directives.MyColDirective'], []);
goog.addDependency('../../../js/directives/MyRowDirective.js', ['Transportation.Directives.MyRowDirective'], []);
goog.addDependency('../../../js/directives/MyTableDirective.js', ['Transportation.Directives.MyTableDirective'], []);
